#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QlSV")]
	public partial class DataConnectDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_bomon(tbl_bomon instance);
    partial void Updatetbl_bomon(tbl_bomon instance);
    partial void Deletetbl_bomon(tbl_bomon instance);
    partial void Inserttbl_diem(tbl_diem instance);
    partial void Updatetbl_diem(tbl_diem instance);
    partial void Deletetbl_diem(tbl_diem instance);
    partial void Inserttbl_hocky(tbl_hocky instance);
    partial void Updatetbl_hocky(tbl_hocky instance);
    partial void Deletetbl_hocky(tbl_hocky instance);
    partial void Inserttbl_khoa(tbl_khoa instance);
    partial void Updatetbl_khoa(tbl_khoa instance);
    partial void Deletetbl_khoa(tbl_khoa instance);
    partial void Inserttbl_khoahoc(tbl_khoahoc instance);
    partial void Updatetbl_khoahoc(tbl_khoahoc instance);
    partial void Deletetbl_khoahoc(tbl_khoahoc instance);
    partial void Inserttbl_lopmh(tbl_lopmh instance);
    partial void Updatetbl_lopmh(tbl_lopmh instance);
    partial void Deletetbl_lopmh(tbl_lopmh instance);
    partial void Inserttbl_lopql(tbl_lopql instance);
    partial void Updatetbl_lopql(tbl_lopql instance);
    partial void Deletetbl_lopql(tbl_lopql instance);
    partial void Inserttbl_monhoc(tbl_monhoc instance);
    partial void Updatetbl_monhoc(tbl_monhoc instance);
    partial void Deletetbl_monhoc(tbl_monhoc instance);
    partial void Inserttbl_namhoc(tbl_namhoc instance);
    partial void Updatetbl_namhoc(tbl_namhoc instance);
    partial void Deletetbl_namhoc(tbl_namhoc instance);
    partial void Inserttbl_sinhvien(tbl_sinhvien instance);
    partial void Updatetbl_sinhvien(tbl_sinhvien instance);
    partial void Deletetbl_sinhvien(tbl_sinhvien instance);
    partial void Inserttbl_taikhoan(tbl_taikhoan instance);
    partial void Updatetbl_taikhoan(tbl_taikhoan instance);
    partial void Deletetbl_taikhoan(tbl_taikhoan instance);
    #endregion
		
		public DataConnectDBDataContext() : 
				base(global::QLSV.Properties.Settings.Default.QlSVConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_bomon> tbl_bomons
		{
			get
			{
				return this.GetTable<tbl_bomon>();
			}
		}
		
		public System.Data.Linq.Table<tbl_diem> tbl_diems
		{
			get
			{
				return this.GetTable<tbl_diem>();
			}
		}
		
		public System.Data.Linq.Table<tbl_hocky> tbl_hockies
		{
			get
			{
				return this.GetTable<tbl_hocky>();
			}
		}
		
		public System.Data.Linq.Table<tbl_khoa> tbl_khoas
		{
			get
			{
				return this.GetTable<tbl_khoa>();
			}
		}
		
		public System.Data.Linq.Table<tbl_khoahoc> tbl_khoahocs
		{
			get
			{
				return this.GetTable<tbl_khoahoc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_lopmh> tbl_lopmhs
		{
			get
			{
				return this.GetTable<tbl_lopmh>();
			}
		}
		
		public System.Data.Linq.Table<tbl_lopql> tbl_lopqls
		{
			get
			{
				return this.GetTable<tbl_lopql>();
			}
		}
		
		public System.Data.Linq.Table<tbl_monhoc> tbl_monhocs
		{
			get
			{
				return this.GetTable<tbl_monhoc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_namhoc> tbl_namhocs
		{
			get
			{
				return this.GetTable<tbl_namhoc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_sinhvien> tbl_sinhviens
		{
			get
			{
				return this.GetTable<tbl_sinhvien>();
			}
		}
		
		public System.Data.Linq.Table<tbl_taikhoan> tbl_taikhoans
		{
			get
			{
				return this.GetTable<tbl_taikhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_bomon")]
	public partial class tbl_bomon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBoMon;
		
		private string _TenBoMon;
		
		private string _GhiChu;
		
		private string _MaKhoa;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _Email;
		
		private EntityRef<tbl_lopmh> _tbl_lopmh;
		
		private EntitySet<tbl_lopql> _tbl_lopqls;
		
		private EntityRef<tbl_khoa> _tbl_khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBoMonChanging(string value);
    partial void OnMaBoMonChanged();
    partial void OnTenBoMonChanging(string value);
    partial void OnTenBoMonChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public tbl_bomon()
		{
			this._tbl_lopmh = default(EntityRef<tbl_lopmh>);
			this._tbl_lopqls = new EntitySet<tbl_lopql>(new Action<tbl_lopql>(this.attach_tbl_lopqls), new Action<tbl_lopql>(this.detach_tbl_lopqls));
			this._tbl_khoa = default(EntityRef<tbl_khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBoMon", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBoMon
		{
			get
			{
				return this._MaBoMon;
			}
			set
			{
				if ((this._MaBoMon != value))
				{
					this.OnMaBoMonChanging(value);
					this.SendPropertyChanging();
					this._MaBoMon = value;
					this.SendPropertyChanged("MaBoMon");
					this.OnMaBoMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBoMon", DbType="NVarChar(50)")]
		public string TenBoMon
		{
			get
			{
				return this._TenBoMon;
			}
			set
			{
				if ((this._TenBoMon != value))
				{
					this.OnTenBoMonChanging(value);
					this.SendPropertyChanging();
					this._TenBoMon = value;
					this.SendPropertyChanged("TenBoMon");
					this.OnTenBoMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NVarChar(10)")]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					if (this._tbl_khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(12)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_bomon_tbl_lopmh", Storage="_tbl_lopmh", ThisKey="MaBoMon", OtherKey="MaLopMH", IsUnique=true, IsForeignKey=false)]
		public tbl_lopmh tbl_lopmh
		{
			get
			{
				return this._tbl_lopmh.Entity;
			}
			set
			{
				tbl_lopmh previousValue = this._tbl_lopmh.Entity;
				if (((previousValue != value) 
							|| (this._tbl_lopmh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_lopmh.Entity = null;
						previousValue.tbl_bomon = null;
					}
					this._tbl_lopmh.Entity = value;
					if ((value != null))
					{
						value.tbl_bomon = this;
					}
					this.SendPropertyChanged("tbl_lopmh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_bomon_tbl_lopql", Storage="_tbl_lopqls", ThisKey="MaBoMon", OtherKey="MaBoMon")]
		public EntitySet<tbl_lopql> tbl_lopqls
		{
			get
			{
				return this._tbl_lopqls;
			}
			set
			{
				this._tbl_lopqls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_khoa_tbl_bomon", Storage="_tbl_khoa", ThisKey="MaKhoa", OtherKey="MaKhoa", IsForeignKey=true)]
		public tbl_khoa tbl_khoa
		{
			get
			{
				return this._tbl_khoa.Entity;
			}
			set
			{
				tbl_khoa previousValue = this._tbl_khoa.Entity;
				if (((previousValue != value) 
							|| (this._tbl_khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_khoa.Entity = null;
						previousValue.tbl_bomons.Remove(this);
					}
					this._tbl_khoa.Entity = value;
					if ((value != null))
					{
						value.tbl_bomons.Add(this);
						this._MaKhoa = value.MaKhoa;
					}
					else
					{
						this._MaKhoa = default(string);
					}
					this.SendPropertyChanged("tbl_khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_lopqls(tbl_lopql entity)
		{
			this.SendPropertyChanging();
			entity.tbl_bomon = this;
		}
		
		private void detach_tbl_lopqls(tbl_lopql entity)
		{
			this.SendPropertyChanging();
			entity.tbl_bomon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_diem")]
	public partial class tbl_diem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaDiem;
		
		private string _MaLopMH;
		
		private string _MaSV;
		
		private System.Nullable<double> _DiemQT;
		
		private System.Nullable<double> _DiemThi;
		
		private string _GhiChu;
		
		private EntityRef<tbl_lopmh> _tbl_lopmh;
		
		private EntityRef<tbl_sinhvien> _tbl_sinhvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDiemChanging(long value);
    partial void OnMaDiemChanged();
    partial void OnMaLopMHChanging(string value);
    partial void OnMaLopMHChanged();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnDiemQTChanging(System.Nullable<double> value);
    partial void OnDiemQTChanged();
    partial void OnDiemThiChanging(System.Nullable<double> value);
    partial void OnDiemThiChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tbl_diem()
		{
			this._tbl_lopmh = default(EntityRef<tbl_lopmh>);
			this._tbl_sinhvien = default(EntityRef<tbl_sinhvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiem", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long MaDiem
		{
			get
			{
				return this._MaDiem;
			}
			set
			{
				if ((this._MaDiem != value))
				{
					this.OnMaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiem = value;
					this.SendPropertyChanged("MaDiem");
					this.OnMaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLopMH", DbType="NVarChar(10)")]
		public string MaLopMH
		{
			get
			{
				return this._MaLopMH;
			}
			set
			{
				if ((this._MaLopMH != value))
				{
					if (this._tbl_lopmh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLopMHChanging(value);
					this.SendPropertyChanging();
					this._MaLopMH = value;
					this.SendPropertyChanged("MaLopMH");
					this.OnMaLopMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(10)")]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					if (this._tbl_sinhvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemQT", DbType="Float")]
		public System.Nullable<double> DiemQT
		{
			get
			{
				return this._DiemQT;
			}
			set
			{
				if ((this._DiemQT != value))
				{
					this.OnDiemQTChanging(value);
					this.SendPropertyChanging();
					this._DiemQT = value;
					this.SendPropertyChanged("DiemQT");
					this.OnDiemQTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemThi", DbType="Float")]
		public System.Nullable<double> DiemThi
		{
			get
			{
				return this._DiemThi;
			}
			set
			{
				if ((this._DiemThi != value))
				{
					this.OnDiemThiChanging(value);
					this.SendPropertyChanging();
					this._DiemThi = value;
					this.SendPropertyChanged("DiemThi");
					this.OnDiemThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lopmh_tbl_diem", Storage="_tbl_lopmh", ThisKey="MaLopMH", OtherKey="MaLopMH", IsForeignKey=true)]
		public tbl_lopmh tbl_lopmh
		{
			get
			{
				return this._tbl_lopmh.Entity;
			}
			set
			{
				tbl_lopmh previousValue = this._tbl_lopmh.Entity;
				if (((previousValue != value) 
							|| (this._tbl_lopmh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_lopmh.Entity = null;
						previousValue.tbl_diems.Remove(this);
					}
					this._tbl_lopmh.Entity = value;
					if ((value != null))
					{
						value.tbl_diems.Add(this);
						this._MaLopMH = value.MaLopMH;
					}
					else
					{
						this._MaLopMH = default(string);
					}
					this.SendPropertyChanged("tbl_lopmh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_sinhvien_tbl_diem", Storage="_tbl_sinhvien", ThisKey="MaSV", OtherKey="MaSV", IsForeignKey=true)]
		public tbl_sinhvien tbl_sinhvien
		{
			get
			{
				return this._tbl_sinhvien.Entity;
			}
			set
			{
				tbl_sinhvien previousValue = this._tbl_sinhvien.Entity;
				if (((previousValue != value) 
							|| (this._tbl_sinhvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_sinhvien.Entity = null;
						previousValue.tbl_diems.Remove(this);
					}
					this._tbl_sinhvien.Entity = value;
					if ((value != null))
					{
						value.tbl_diems.Add(this);
						this._MaSV = value.MaSV;
					}
					else
					{
						this._MaSV = default(string);
					}
					this.SendPropertyChanged("tbl_sinhvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_hocky")]
	public partial class tbl_hocky : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHocKy;
		
		private string _TenHocKy;
		
		private string _GhiChu;
		
		private EntitySet<tbl_lopmh> _tbl_lopmhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHocKyChanging(string value);
    partial void OnMaHocKyChanged();
    partial void OnTenHocKyChanging(string value);
    partial void OnTenHocKyChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tbl_hocky()
		{
			this._tbl_lopmhs = new EntitySet<tbl_lopmh>(new Action<tbl_lopmh>(this.attach_tbl_lopmhs), new Action<tbl_lopmh>(this.detach_tbl_lopmhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocKy", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHocKy
		{
			get
			{
				return this._MaHocKy;
			}
			set
			{
				if ((this._MaHocKy != value))
				{
					this.OnMaHocKyChanging(value);
					this.SendPropertyChanging();
					this._MaHocKy = value;
					this.SendPropertyChanged("MaHocKy");
					this.OnMaHocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHocKy", DbType="NVarChar(50)")]
		public string TenHocKy
		{
			get
			{
				return this._TenHocKy;
			}
			set
			{
				if ((this._TenHocKy != value))
				{
					this.OnTenHocKyChanging(value);
					this.SendPropertyChanging();
					this._TenHocKy = value;
					this.SendPropertyChanged("TenHocKy");
					this.OnTenHocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_hocky_tbl_lopmh", Storage="_tbl_lopmhs", ThisKey="MaHocKy", OtherKey="MaHocKy")]
		public EntitySet<tbl_lopmh> tbl_lopmhs
		{
			get
			{
				return this._tbl_lopmhs;
			}
			set
			{
				this._tbl_lopmhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_lopmhs(tbl_lopmh entity)
		{
			this.SendPropertyChanging();
			entity.tbl_hocky = this;
		}
		
		private void detach_tbl_lopmhs(tbl_lopmh entity)
		{
			this.SendPropertyChanging();
			entity.tbl_hocky = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_khoa")]
	public partial class tbl_khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhoa;
		
		private string _TenKhoa;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _Email;
		
		private EntitySet<tbl_bomon> _tbl_bomons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnTenKhoaChanging(string value);
    partial void OnTenKhoaChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public tbl_khoa()
		{
			this._tbl_bomons = new EntitySet<tbl_bomon>(new Action<tbl_bomon>(this.attach_tbl_bomons), new Action<tbl_bomon>(this.detach_tbl_bomons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoa", DbType="NVarChar(50)")]
		public string TenKhoa
		{
			get
			{
				return this._TenKhoa;
			}
			set
			{
				if ((this._TenKhoa != value))
				{
					this.OnTenKhoaChanging(value);
					this.SendPropertyChanging();
					this._TenKhoa = value;
					this.SendPropertyChanged("TenKhoa");
					this.OnTenKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(12)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_khoa_tbl_bomon", Storage="_tbl_bomons", ThisKey="MaKhoa", OtherKey="MaKhoa")]
		public EntitySet<tbl_bomon> tbl_bomons
		{
			get
			{
				return this._tbl_bomons;
			}
			set
			{
				this._tbl_bomons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_bomons(tbl_bomon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_khoa = this;
		}
		
		private void detach_tbl_bomons(tbl_bomon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_khoa = null;
		}

        public string MaKhoaHoc { get; set; }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_khoahoc")]
	public partial class tbl_khoahoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhoaHoc;
		
		private string _TenKhoaHoc;
		
		private string _GhiChu;
		
		private EntitySet<tbl_lopql> _tbl_lopqls;
		
		private EntitySet<tbl_sinhvien> _tbl_sinhviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoaHocChanging(string value);
    partial void OnMaKhoaHocChanged();
    partial void OnTenKhoaHocChanging(string value);
    partial void OnTenKhoaHocChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tbl_khoahoc()
		{
			this._tbl_lopqls = new EntitySet<tbl_lopql>(new Action<tbl_lopql>(this.attach_tbl_lopqls), new Action<tbl_lopql>(this.detach_tbl_lopqls));
			this._tbl_sinhviens = new EntitySet<tbl_sinhvien>(new Action<tbl_sinhvien>(this.attach_tbl_sinhviens), new Action<tbl_sinhvien>(this.detach_tbl_sinhviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoaHoc", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoaHoc
		{
			get
			{
				return this._MaKhoaHoc;
			}
			set
			{
				if ((this._MaKhoaHoc != value))
				{
					this.OnMaKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._MaKhoaHoc = value;
					this.SendPropertyChanged("MaKhoaHoc");
					this.OnMaKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoaHoc", DbType="NVarChar(50)")]
		public string TenKhoaHoc
		{
			get
			{
				return this._TenKhoaHoc;
			}
			set
			{
				if ((this._TenKhoaHoc != value))
				{
					this.OnTenKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._TenKhoaHoc = value;
					this.SendPropertyChanged("TenKhoaHoc");
					this.OnTenKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_khoahoc_tbl_lopql", Storage="_tbl_lopqls", ThisKey="MaKhoaHoc", OtherKey="MaKhoaHoc")]
		public EntitySet<tbl_lopql> tbl_lopqls
		{
			get
			{
				return this._tbl_lopqls;
			}
			set
			{
				this._tbl_lopqls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_khoahoc_tbl_sinhvien", Storage="_tbl_sinhviens", ThisKey="MaKhoaHoc", OtherKey="MaKhoaHoc")]
		public EntitySet<tbl_sinhvien> tbl_sinhviens
		{
			get
			{
				return this._tbl_sinhviens;
			}
			set
			{
				this._tbl_sinhviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_lopqls(tbl_lopql entity)
		{
			this.SendPropertyChanging();
			entity.tbl_khoahoc = this;
		}
		
		private void detach_tbl_lopqls(tbl_lopql entity)
		{
			this.SendPropertyChanging();
			entity.tbl_khoahoc = null;
		}
		
		private void attach_tbl_sinhviens(tbl_sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_khoahoc = this;
		}
		
		private void detach_tbl_sinhviens(tbl_sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_khoahoc = null;
		}

        public string MaKhoa { get; set; }

        public string TenKhoa { get; set; }

        public string DiaChi { get; set; }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lopmh")]
	public partial class tbl_lopmh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLopMH;
		
		private string _TenLopMH;
		
		private string _MaMon;
		
		private string _MaHocKy;
		
		private string _MaNamHoc;
		
		private EntitySet<tbl_diem> _tbl_diems;
		
		private EntityRef<tbl_monhoc> _tbl_monhoc;
		
		private EntityRef<tbl_bomon> _tbl_bomon;
		
		private EntityRef<tbl_hocky> _tbl_hocky;
		
		private EntityRef<tbl_namhoc> _tbl_namhoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLopMHChanging(string value);
    partial void OnMaLopMHChanged();
    partial void OnTenLopMHChanging(string value);
    partial void OnTenLopMHChanged();
    partial void OnMaMonChanging(string value);
    partial void OnMaMonChanged();
    partial void OnMaHocKyChanging(string value);
    partial void OnMaHocKyChanged();
    partial void OnMaNamHocChanging(string value);
    partial void OnMaNamHocChanged();
    #endregion
		
		public tbl_lopmh()
		{
			this._tbl_diems = new EntitySet<tbl_diem>(new Action<tbl_diem>(this.attach_tbl_diems), new Action<tbl_diem>(this.detach_tbl_diems));
			this._tbl_monhoc = default(EntityRef<tbl_monhoc>);
			this._tbl_bomon = default(EntityRef<tbl_bomon>);
			this._tbl_hocky = default(EntityRef<tbl_hocky>);
			this._tbl_namhoc = default(EntityRef<tbl_namhoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLopMH", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLopMH
		{
			get
			{
				return this._MaLopMH;
			}
			set
			{
				if ((this._MaLopMH != value))
				{
					if (this._tbl_bomon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLopMHChanging(value);
					this.SendPropertyChanging();
					this._MaLopMH = value;
					this.SendPropertyChanged("MaLopMH");
					this.OnMaLopMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLopMH", DbType="NVarChar(50)")]
		public string TenLopMH
		{
			get
			{
				return this._TenLopMH;
			}
			set
			{
				if ((this._TenLopMH != value))
				{
					this.OnTenLopMHChanging(value);
					this.SendPropertyChanging();
					this._TenLopMH = value;
					this.SendPropertyChanged("TenLopMH");
					this.OnTenLopMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NVarChar(10)")]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocKy", DbType="NVarChar(10)")]
		public string MaHocKy
		{
			get
			{
				return this._MaHocKy;
			}
			set
			{
				if ((this._MaHocKy != value))
				{
					if (this._tbl_hocky.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHocKyChanging(value);
					this.SendPropertyChanging();
					this._MaHocKy = value;
					this.SendPropertyChanged("MaHocKy");
					this.OnMaHocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNamHoc", DbType="NVarChar(10)")]
		public string MaNamHoc
		{
			get
			{
				return this._MaNamHoc;
			}
			set
			{
				if ((this._MaNamHoc != value))
				{
					if (this._tbl_namhoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNamHocChanging(value);
					this.SendPropertyChanging();
					this._MaNamHoc = value;
					this.SendPropertyChanged("MaNamHoc");
					this.OnMaNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lopmh_tbl_diem", Storage="_tbl_diems", ThisKey="MaLopMH", OtherKey="MaLopMH")]
		public EntitySet<tbl_diem> tbl_diems
		{
			get
			{
				return this._tbl_diems;
			}
			set
			{
				this._tbl_diems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lopmh_tbl_monhoc", Storage="_tbl_monhoc", ThisKey="MaLopMH", OtherKey="MaMon", IsUnique=true, IsForeignKey=false)]
		public tbl_monhoc tbl_monhoc
		{
			get
			{
				return this._tbl_monhoc.Entity;
			}
			set
			{
				tbl_monhoc previousValue = this._tbl_monhoc.Entity;
				if (((previousValue != value) 
							|| (this._tbl_monhoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_monhoc.Entity = null;
						previousValue.tbl_lopmh = null;
					}
					this._tbl_monhoc.Entity = value;
					if ((value != null))
					{
						value.tbl_lopmh = this;
					}
					this.SendPropertyChanged("tbl_monhoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_bomon_tbl_lopmh", Storage="_tbl_bomon", ThisKey="MaLopMH", OtherKey="MaBoMon", IsForeignKey=true)]
		public tbl_bomon tbl_bomon
		{
			get
			{
				return this._tbl_bomon.Entity;
			}
			set
			{
				tbl_bomon previousValue = this._tbl_bomon.Entity;
				if (((previousValue != value) 
							|| (this._tbl_bomon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_bomon.Entity = null;
						previousValue.tbl_lopmh = null;
					}
					this._tbl_bomon.Entity = value;
					if ((value != null))
					{
						value.tbl_lopmh = this;
						this._MaLopMH = value.MaBoMon;
					}
					else
					{
						this._MaLopMH = default(string);
					}
					this.SendPropertyChanged("tbl_bomon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_hocky_tbl_lopmh", Storage="_tbl_hocky", ThisKey="MaHocKy", OtherKey="MaHocKy", IsForeignKey=true)]
		public tbl_hocky tbl_hocky
		{
			get
			{
				return this._tbl_hocky.Entity;
			}
			set
			{
				tbl_hocky previousValue = this._tbl_hocky.Entity;
				if (((previousValue != value) 
							|| (this._tbl_hocky.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_hocky.Entity = null;
						previousValue.tbl_lopmhs.Remove(this);
					}
					this._tbl_hocky.Entity = value;
					if ((value != null))
					{
						value.tbl_lopmhs.Add(this);
						this._MaHocKy = value.MaHocKy;
					}
					else
					{
						this._MaHocKy = default(string);
					}
					this.SendPropertyChanged("tbl_hocky");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_namhoc_tbl_lopmh", Storage="_tbl_namhoc", ThisKey="MaNamHoc", OtherKey="MaNamHoc", IsForeignKey=true)]
		public tbl_namhoc tbl_namhoc
		{
			get
			{
				return this._tbl_namhoc.Entity;
			}
			set
			{
				tbl_namhoc previousValue = this._tbl_namhoc.Entity;
				if (((previousValue != value) 
							|| (this._tbl_namhoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_namhoc.Entity = null;
						previousValue.tbl_lopmhs.Remove(this);
					}
					this._tbl_namhoc.Entity = value;
					if ((value != null))
					{
						value.tbl_lopmhs.Add(this);
						this._MaNamHoc = value.MaNamHoc;
					}
					else
					{
						this._MaNamHoc = default(string);
					}
					this.SendPropertyChanged("tbl_namhoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_diems(tbl_diem entity)
		{
			this.SendPropertyChanging();
			entity.tbl_lopmh = this;
		}
		
		private void detach_tbl_diems(tbl_diem entity)
		{
			this.SendPropertyChanging();
			entity.tbl_lopmh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lopql")]
	public partial class tbl_lopql : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLopQL;
		
		private string _TenLopQL;
		
		private System.Nullable<int> _SiSo;
		
		private string _MaBoMon;
		
		private string _MaKhoaHoc;
		
		private EntitySet<tbl_sinhvien> _tbl_sinhviens;
		
		private EntityRef<tbl_bomon> _tbl_bomon;
		
		private EntityRef<tbl_khoahoc> _tbl_khoahoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLopQLChanging(string value);
    partial void OnMaLopQLChanged();
    partial void OnTenLopQLChanging(string value);
    partial void OnTenLopQLChanged();
    partial void OnSiSoChanging(System.Nullable<int> value);
    partial void OnSiSoChanged();
    partial void OnMaBoMonChanging(string value);
    partial void OnMaBoMonChanged();
    partial void OnMaKhoaHocChanging(string value);
    partial void OnMaKhoaHocChanged();
    #endregion
		
		public tbl_lopql()
		{
			this._tbl_sinhviens = new EntitySet<tbl_sinhvien>(new Action<tbl_sinhvien>(this.attach_tbl_sinhviens), new Action<tbl_sinhvien>(this.detach_tbl_sinhviens));
			this._tbl_bomon = default(EntityRef<tbl_bomon>);
			this._tbl_khoahoc = default(EntityRef<tbl_khoahoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLopQL", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLopQL
		{
			get
			{
				return this._MaLopQL;
			}
			set
			{
				if ((this._MaLopQL != value))
				{
					this.OnMaLopQLChanging(value);
					this.SendPropertyChanging();
					this._MaLopQL = value;
					this.SendPropertyChanged("MaLopQL");
					this.OnMaLopQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLopQL", DbType="NVarChar(50)")]
		public string TenLopQL
		{
			get
			{
				return this._TenLopQL;
			}
			set
			{
				if ((this._TenLopQL != value))
				{
					this.OnTenLopQLChanging(value);
					this.SendPropertyChanging();
					this._TenLopQL = value;
					this.SendPropertyChanged("TenLopQL");
					this.OnTenLopQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiSo", DbType="Int")]
		public System.Nullable<int> SiSo
		{
			get
			{
				return this._SiSo;
			}
			set
			{
				if ((this._SiSo != value))
				{
					this.OnSiSoChanging(value);
					this.SendPropertyChanging();
					this._SiSo = value;
					this.SendPropertyChanged("SiSo");
					this.OnSiSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBoMon", DbType="NVarChar(10)")]
		public string MaBoMon
		{
			get
			{
				return this._MaBoMon;
			}
			set
			{
				if ((this._MaBoMon != value))
				{
					if (this._tbl_bomon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBoMonChanging(value);
					this.SendPropertyChanging();
					this._MaBoMon = value;
					this.SendPropertyChanged("MaBoMon");
					this.OnMaBoMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoaHoc", DbType="NVarChar(10)")]
		public string MaKhoaHoc
		{
			get
			{
				return this._MaKhoaHoc;
			}
			set
			{
				if ((this._MaKhoaHoc != value))
				{
					if (this._tbl_khoahoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._MaKhoaHoc = value;
					this.SendPropertyChanged("MaKhoaHoc");
					this.OnMaKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lopql_tbl_sinhvien", Storage="_tbl_sinhviens", ThisKey="MaLopQL", OtherKey="MaLopQL")]
		public EntitySet<tbl_sinhvien> tbl_sinhviens
		{
			get
			{
				return this._tbl_sinhviens;
			}
			set
			{
				this._tbl_sinhviens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_bomon_tbl_lopql", Storage="_tbl_bomon", ThisKey="MaBoMon", OtherKey="MaBoMon", IsForeignKey=true)]
		public tbl_bomon tbl_bomon
		{
			get
			{
				return this._tbl_bomon.Entity;
			}
			set
			{
				tbl_bomon previousValue = this._tbl_bomon.Entity;
				if (((previousValue != value) 
							|| (this._tbl_bomon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_bomon.Entity = null;
						previousValue.tbl_lopqls.Remove(this);
					}
					this._tbl_bomon.Entity = value;
					if ((value != null))
					{
						value.tbl_lopqls.Add(this);
						this._MaBoMon = value.MaBoMon;
					}
					else
					{
						this._MaBoMon = default(string);
					}
					this.SendPropertyChanged("tbl_bomon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_khoahoc_tbl_lopql", Storage="_tbl_khoahoc", ThisKey="MaKhoaHoc", OtherKey="MaKhoaHoc", IsForeignKey=true)]
		public tbl_khoahoc tbl_khoahoc
		{
			get
			{
				return this._tbl_khoahoc.Entity;
			}
			set
			{
				tbl_khoahoc previousValue = this._tbl_khoahoc.Entity;
				if (((previousValue != value) 
							|| (this._tbl_khoahoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_khoahoc.Entity = null;
						previousValue.tbl_lopqls.Remove(this);
					}
					this._tbl_khoahoc.Entity = value;
					if ((value != null))
					{
						value.tbl_lopqls.Add(this);
						this._MaKhoaHoc = value.MaKhoaHoc;
					}
					else
					{
						this._MaKhoaHoc = default(string);
					}
					this.SendPropertyChanged("tbl_khoahoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_sinhviens(tbl_sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_lopql = this;
		}
		
		private void detach_tbl_sinhviens(tbl_sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_lopql = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_monhoc")]
	public partial class tbl_monhoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMon;
		
		private string _TenMon;
		
		private string _GhiChu;
		
		private string _MaBoMon;
		
		private System.Nullable<int> _SoTinChi;
		
		private EntityRef<tbl_lopmh> _tbl_lopmh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMonChanging(string value);
    partial void OnMaMonChanged();
    partial void OnTenMonChanging(string value);
    partial void OnTenMonChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnMaBoMonChanging(string value);
    partial void OnMaBoMonChanged();
    partial void OnSoTinChiChanging(System.Nullable<int> value);
    partial void OnSoTinChiChanged();
    #endregion
		
		public tbl_monhoc()
		{
			this._tbl_lopmh = default(EntityRef<tbl_lopmh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					if (this._tbl_lopmh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMon", DbType="NVarChar(50)")]
		public string TenMon
		{
			get
			{
				return this._TenMon;
			}
			set
			{
				if ((this._TenMon != value))
				{
					this.OnTenMonChanging(value);
					this.SendPropertyChanging();
					this._TenMon = value;
					this.SendPropertyChanged("TenMon");
					this.OnTenMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBoMon", DbType="NVarChar(10)")]
		public string MaBoMon
		{
			get
			{
				return this._MaBoMon;
			}
			set
			{
				if ((this._MaBoMon != value))
				{
					this.OnMaBoMonChanging(value);
					this.SendPropertyChanging();
					this._MaBoMon = value;
					this.SendPropertyChanged("MaBoMon");
					this.OnMaBoMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTinChi", DbType="Int")]
		public System.Nullable<int> SoTinChi
		{
			get
			{
				return this._SoTinChi;
			}
			set
			{
				if ((this._SoTinChi != value))
				{
					this.OnSoTinChiChanging(value);
					this.SendPropertyChanging();
					this._SoTinChi = value;
					this.SendPropertyChanged("SoTinChi");
					this.OnSoTinChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lopmh_tbl_monhoc", Storage="_tbl_lopmh", ThisKey="MaMon", OtherKey="MaLopMH", IsForeignKey=true)]
		public tbl_lopmh tbl_lopmh
		{
			get
			{
				return this._tbl_lopmh.Entity;
			}
			set
			{
				tbl_lopmh previousValue = this._tbl_lopmh.Entity;
				if (((previousValue != value) 
							|| (this._tbl_lopmh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_lopmh.Entity = null;
						previousValue.tbl_monhoc = null;
					}
					this._tbl_lopmh.Entity = value;
					if ((value != null))
					{
						value.tbl_monhoc = this;
						this._MaMon = value.MaLopMH;
					}
					else
					{
						this._MaMon = default(string);
					}
					this.SendPropertyChanged("tbl_lopmh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_namhoc")]
	public partial class tbl_namhoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNamHoc;
		
		private string _TenNamHoc;
		
		private string _GhiChu;
		
		private EntitySet<tbl_lopmh> _tbl_lopmhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNamHocChanging(string value);
    partial void OnMaNamHocChanged();
    partial void OnTenNamHocChanging(string value);
    partial void OnTenNamHocChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tbl_namhoc()
		{
			this._tbl_lopmhs = new EntitySet<tbl_lopmh>(new Action<tbl_lopmh>(this.attach_tbl_lopmhs), new Action<tbl_lopmh>(this.detach_tbl_lopmhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNamHoc", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNamHoc
		{
			get
			{
				return this._MaNamHoc;
			}
			set
			{
				if ((this._MaNamHoc != value))
				{
					this.OnMaNamHocChanging(value);
					this.SendPropertyChanging();
					this._MaNamHoc = value;
					this.SendPropertyChanged("MaNamHoc");
					this.OnMaNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNamHoc", DbType="NVarChar(50)")]
		public string TenNamHoc
		{
			get
			{
				return this._TenNamHoc;
			}
			set
			{
				if ((this._TenNamHoc != value))
				{
					this.OnTenNamHocChanging(value);
					this.SendPropertyChanging();
					this._TenNamHoc = value;
					this.SendPropertyChanged("TenNamHoc");
					this.OnTenNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_namhoc_tbl_lopmh", Storage="_tbl_lopmhs", ThisKey="MaNamHoc", OtherKey="MaNamHoc")]
		public EntitySet<tbl_lopmh> tbl_lopmhs
		{
			get
			{
				return this._tbl_lopmhs;
			}
			set
			{
				this._tbl_lopmhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_lopmhs(tbl_lopmh entity)
		{
			this.SendPropertyChanging();
			entity.tbl_namhoc = this;
		}
		
		private void detach_tbl_lopmhs(tbl_lopmh entity)
		{
			this.SendPropertyChanging();
			entity.tbl_namhoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_sinhvien")]
	public partial class tbl_sinhvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<bool> _GioiTinh;
		
		private string _QueQuan;
		
		private string _MaLopQL;
		
		private string _MaKhoaHoc;
		
		private EntitySet<tbl_diem> _tbl_diems;
		
		private EntityRef<tbl_khoahoc> _tbl_khoahoc;
		
		private EntityRef<tbl_lopql> _tbl_lopql;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnQueQuanChanging(string value);
    partial void OnQueQuanChanged();
    partial void OnMaLopQLChanging(string value);
    partial void OnMaLopQLChanged();
    partial void OnMaKhoaHocChanging(string value);
    partial void OnMaKhoaHocChanged();
    #endregion
		
		public tbl_sinhvien()
		{
			this._tbl_diems = new EntitySet<tbl_diem>(new Action<tbl_diem>(this.attach_tbl_diems), new Action<tbl_diem>(this.detach_tbl_diems));
			this._tbl_khoahoc = default(EntityRef<tbl_khoahoc>);
			this._tbl_lopql = default(EntityRef<tbl_lopql>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					this.OnQueQuanChanging(value);
					this.SendPropertyChanging();
					this._QueQuan = value;
					this.SendPropertyChanged("QueQuan");
					this.OnQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLopQL", DbType="NVarChar(10)")]
		public string MaLopQL
		{
			get
			{
				return this._MaLopQL;
			}
			set
			{
				if ((this._MaLopQL != value))
				{
					if (this._tbl_lopql.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLopQLChanging(value);
					this.SendPropertyChanging();
					this._MaLopQL = value;
					this.SendPropertyChanged("MaLopQL");
					this.OnMaLopQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoaHoc", DbType="NVarChar(10)")]
		public string MaKhoaHoc
		{
			get
			{
				return this._MaKhoaHoc;
			}
			set
			{
				if ((this._MaKhoaHoc != value))
				{
					if (this._tbl_khoahoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._MaKhoaHoc = value;
					this.SendPropertyChanged("MaKhoaHoc");
					this.OnMaKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_sinhvien_tbl_diem", Storage="_tbl_diems", ThisKey="MaSV", OtherKey="MaSV")]
		public EntitySet<tbl_diem> tbl_diems
		{
			get
			{
				return this._tbl_diems;
			}
			set
			{
				this._tbl_diems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_khoahoc_tbl_sinhvien", Storage="_tbl_khoahoc", ThisKey="MaKhoaHoc", OtherKey="MaKhoaHoc", IsForeignKey=true)]
		public tbl_khoahoc tbl_khoahoc
		{
			get
			{
				return this._tbl_khoahoc.Entity;
			}
			set
			{
				tbl_khoahoc previousValue = this._tbl_khoahoc.Entity;
				if (((previousValue != value) 
							|| (this._tbl_khoahoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_khoahoc.Entity = null;
						previousValue.tbl_sinhviens.Remove(this);
					}
					this._tbl_khoahoc.Entity = value;
					if ((value != null))
					{
						value.tbl_sinhviens.Add(this);
						this._MaKhoaHoc = value.MaKhoaHoc;
					}
					else
					{
						this._MaKhoaHoc = default(string);
					}
					this.SendPropertyChanged("tbl_khoahoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_lopql_tbl_sinhvien", Storage="_tbl_lopql", ThisKey="MaLopQL", OtherKey="MaLopQL", IsForeignKey=true)]
		public tbl_lopql tbl_lopql
		{
			get
			{
				return this._tbl_lopql.Entity;
			}
			set
			{
				tbl_lopql previousValue = this._tbl_lopql.Entity;
				if (((previousValue != value) 
							|| (this._tbl_lopql.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_lopql.Entity = null;
						previousValue.tbl_sinhviens.Remove(this);
					}
					this._tbl_lopql.Entity = value;
					if ((value != null))
					{
						value.tbl_sinhviens.Add(this);
						this._MaLopQL = value.MaLopQL;
					}
					else
					{
						this._MaLopQL = default(string);
					}
					this.SendPropertyChanged("tbl_lopql");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_diems(tbl_diem entity)
		{
			this.SendPropertyChanging();
			entity.tbl_sinhvien = this;
		}
		
		private void detach_tbl_diems(tbl_diem entity)
		{
			this.SendPropertyChanging();
			entity.tbl_sinhvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_taikhoan")]
	public partial class tbl_taikhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private string _Email;
		
		private string _SDT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public tbl_taikhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(30)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(12)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
